/**
 * Mock data for the SEO Dashboard
 *
 * This simulates realistic data based on common issues found in
 * template-heavy location page sites. In production, this would
 * be generated by running the actual analyzers.
 */

import { SEOReport, SEOIssue, LinkGraphAnalysis, BlogConnectionAnalysis, ContentDepthAnalysis, PageLinkData, PageContentAnalysis } from '@/types/seo';

// Generate realistic orphan pages
const generateOrphanPages = (): PageLinkData[] => {
  const pages: PageLinkData[] = [];
  const services = [
    'spray-foam-insulation', 'attic-insulation', 'home-insulation',
    'commercial-insulation', 'insulation-removal', 'insulation-contractor',
    'insulation-company', 'metal-building-insulation', 'pole-barn-insulation',
    'warehouse-insulation', 'new-construction-insulation'
  ];
  const cities = [
    'ackerly', 'andrews', 'anton', 'big-spring', 'bledsoe', 'brownfield',
    'coahoma', 'denver-city', 'forsan', 'gail', 'garden-city', 'goldsmith',
    'kermit', 'lamesa', 'levelland', 'loop', 'lubbock', 'midland', 'morton',
    'odessa', 'plains', 'post', 'seminole', 'slaton', 'stanton', 'tahoka'
  ];

  // Most location pages are orphans
  for (let i = 0; i < 400; i++) {
    const service = services[i % services.length];
    const city = cities[i % cities.length];
    pages.push({
      url: `/${service}-${city}-tx/`,
      title: '',
      incomingLinks: i < 50 ? ['/sitemap/'] : [],
      outgoingLinks: ['/', '/contact-us/', `/${service}/`],
      incomingCount: i < 50 ? 1 : 0,
      outgoingCount: 3,
      linkDepth: 3,
      isOrphan: true,
      anchorTexts: [],
    });
  }

  return pages;
};

// Generate mock issues
const mockIssues: SEOIssue[] = [
  {
    id: 'location-pages-isolated',
    severity: 'critical',
    category: 'Internal Linking',
    title: '650+ location pages have almost no internal links',
    description: 'Location pages only receive links from the sitemap page but have no contextual links from blog posts, service pages, or other location pages. They are essentially orphaned.',
    affectedPages: generateOrphanPages().slice(0, 20).map(p => p.url),
    recommendation: 'Create "nearby areas" links between location pages. Add location mentions with links in blog posts. Service pages should link to top locations.',
    impact: 'Location pages have minimal link equity and may not rank well despite existing.',
  },
  {
    id: 'services-no-blog-coverage',
    severity: 'critical',
    category: 'Content Gaps',
    title: '7 of 11 services have ZERO blog mentions',
    description: 'These services are not mentioned in any blog content: home-insulation, insulation-removal, insulation-company, metal-building-insulation, pole-barn-insulation, warehouse-insulation, new-construction-insulation',
    affectedPages: [
      '/home-insulation/',
      '/insulation-removal/',
      '/insulation-company/',
      '/metal-building-insulation/',
      '/pole-barn-insulation/',
      '/warehouse-insulation/',
      '/new-construction-insulation/',
    ],
    recommendation: 'Create dedicated blog posts for each service covering benefits, process, FAQs, and case studies.',
    impact: 'Service pages lack supporting content to build topical authority.',
  },
  {
    id: 'blog-not-linking-services',
    severity: 'critical',
    category: 'Internal Linking',
    title: 'Blog posts average only 0.5 links to service pages',
    description: 'Blog posts mention services but rarely include actual links. This wastes the opportunity to pass link equity to important commercial pages.',
    affectedPages: ['/blog/'],
    recommendation: 'Each blog post should include 2-3 contextual links to relevant service pages.',
    impact: 'Blog content is not effectively supporting service page rankings.',
  },
  {
    id: 'thin-content-majority',
    severity: 'critical',
    category: 'Content Quality',
    title: '85% of pages have less than 300 words of unique content',
    description: 'Most pages rely heavily on template content with only the city/service name changed. The actual unique, valuable content per page is minimal.',
    affectedPages: [],
    recommendation: 'Add location-specific information: local weather considerations, regional building types, nearby project examples, area-specific FAQs.',
    impact: 'Google may see these as thin content or near-duplicates, limiting ranking potential.',
  },
  {
    id: 'duplicate-meta-descriptions',
    severity: 'warning',
    category: 'Technical SEO',
    title: '600+ pages share templated meta descriptions',
    description: 'Meta descriptions follow the same template pattern with only city names swapped. This provides no differentiation in search results.',
    affectedPages: generateOrphanPages().slice(0, 15).map(p => p.url),
    recommendation: 'Write unique meta descriptions that highlight specific value propositions for each page.',
    impact: 'Identical metas reduce click-through rates and make pages indistinguishable in search results.',
  },
  {
    id: 'low-blog-count',
    severity: 'warning',
    category: 'Content Strategy',
    title: 'Only 6 blog posts for 11 services',
    description: 'The blog has minimal content. Each service should have at least 3-5 supporting articles.',
    affectedPages: ['/blog/'],
    recommendation: 'Create a content calendar targeting 2-4 blog posts per month covering different services and locations.',
    impact: 'Limited content means limited opportunities to rank for informational queries and build authority.',
  },
  {
    id: 'blog-not-linking-locations',
    severity: 'warning',
    category: 'Internal Linking',
    title: 'Blog posts have ZERO links to location pages',
    description: 'Blog content never links to any location-specific service pages, even when mentioning areas.',
    affectedPages: ['/blog/'],
    recommendation: 'When mentioning West Texas, Seminole, or other areas in blog posts, link to relevant location pages.',
    impact: 'Location pages receive no contextual link support from content.',
  },
  {
    id: 'service-pages-no-faq',
    severity: 'opportunity',
    category: 'Content Enhancement',
    title: '8 service pages have no FAQ sections',
    description: 'Service pages lack FAQ content that could help answer common questions and improve search visibility.',
    affectedPages: [
      '/home-insulation/',
      '/commercial-insulation/',
      '/insulation-removal/',
      '/insulation-company/',
      '/metal-building-insulation/',
      '/pole-barn-insulation/',
      '/warehouse-insulation/',
      '/new-construction-insulation/',
    ],
    recommendation: 'Add FAQ sections with schema markup covering common customer questions for each service.',
    impact: 'Missing opportunity for rich results and comprehensive content.',
  },
  {
    id: 'location-no-cross-links',
    severity: 'opportunity',
    category: 'Internal Linking',
    title: 'Location pages don\'t link to nearby areas',
    description: 'Each location page could link to related nearby cities to create a network of interconnected pages.',
    affectedPages: [],
    recommendation: 'Add a "Nearby Service Areas" section to each location page linking to 3-5 adjacent cities.',
    impact: 'Missing opportunity to distribute link equity and help users find relevant locations.',
  },
  {
    id: 'no-case-studies',
    severity: 'opportunity',
    category: 'Content Strategy',
    title: 'No project case studies or portfolio content',
    description: 'There are no detailed case studies showing completed projects, which could provide unique content for location pages.',
    affectedPages: [],
    recommendation: 'Create case study content for completed projects, linking to relevant location and service pages.',
    impact: 'Missing unique, valuable content that differentiates from competitors.',
  },
];

// Link Analysis Mock
const mockLinkAnalysis: LinkGraphAnalysis = {
  totalPages: 726,
  totalInternalLinks: 2100,
  orphanPages: generateOrphanPages(),
  weaklyLinkedPages: generateOrphanPages().slice(0, 50).map(p => ({ ...p, incomingCount: 2 })),
  hubPages: [
    { url: '/', title: 'Home', incomingLinks: [], outgoingLinks: [], incomingCount: 50, outgoingCount: 45, linkDepth: 0, isOrphan: false, anchorTexts: [] },
    { url: '/sitemap/', title: 'Sitemap', incomingLinks: [], outgoingLinks: [], incomingCount: 10, outgoingCount: 726, linkDepth: 1, isOrphan: false, anchorTexts: [] },
    { url: '/services/', title: 'Services', incomingLinks: [], outgoingLinks: [], incomingCount: 25, outgoingCount: 15, linkDepth: 1, isOrphan: false, anchorTexts: [] },
  ],
  authorityPages: [
    { url: '/', title: 'Home', incomingLinks: [], outgoingLinks: [], incomingCount: 726, outgoingCount: 45, linkDepth: 0, isOrphan: false, anchorTexts: [] },
    { url: '/contact-us/', title: 'Contact', incomingLinks: [], outgoingLinks: [], incomingCount: 700, outgoingCount: 5, linkDepth: 1, isOrphan: false, anchorTexts: [] },
    { url: '/spray-foam-insulation/', title: 'Spray Foam', incomingLinks: [], outgoingLinks: [], incomingCount: 150, outgoingCount: 12, linkDepth: 1, isOrphan: false, anchorTexts: [] },
  ],
  averageLinksPerPage: 2.9,
  maxLinkDepth: 4,
  unreachablePages: [],
  linkDistribution: {
    zeroLinks: 450,
    oneToTwo: 200,
    threeToFive: 50,
    sixToTen: 15,
    moreThanTen: 11,
  },
};

// Blog Analysis Mock
const mockBlogAnalysis: BlogConnectionAnalysis = {
  totalBlogPosts: 6,
  servicesNeverMentioned: [
    'home-insulation',
    'insulation-removal',
    'insulation-company',
    'metal-building-insulation',
    'pole-barn-insulation',
    'warehouse-insulation',
    'new-construction-insulation',
  ],
  locationsNeverMentioned: [
    'ackerly', 'anton', 'bledsoe', 'bula', 'coahoma', 'enochs', 'forsan',
    'gail', 'garden-city', 'gardendale', 'goldsmith', 'knott', 'lenorah',
    // ... many more
  ],
  servicesWithBlogCoverage: [
    { service: 'spray-foam-insulation', mentionCount: 4, blogPosts: ['/blog/benefits-of-spray-foam-insulation/', '/blog/open-cell-vs-closed-cell/'] },
    { service: 'attic-insulation', mentionCount: 2, blogPosts: ['/blog/when-to-replace-insulation/'] },
    { service: 'commercial-insulation', mentionCount: 1, blogPosts: ['/blog/commercial-insulation-guide/'] },
    { service: 'insulation-contractor', mentionCount: 1, blogPosts: ['/blog/energy-savings-insulation/'] },
  ],
  locationsWithBlogCoverage: [
    { location: 'seminole', mentionCount: 2, blogPosts: ['/blog/preparing-for-texas-summers/'] },
    { location: 'west-texas', mentionCount: 3, blogPosts: ['/blog/preparing-for-texas-summers/', '/blog/energy-savings-insulation/'] },
  ],
  blogToServiceLinks: 3,
  blogToLocationLinks: 0,
  averageBlogWordCount: 650,
  staleBlogPosts: [],
};

// Content Analysis Mock
const mockContentAnalysis: ContentDepthAnalysis = {
  thinContentPages: generateOrphanPages().slice(0, 100).map(p => ({
    url: p.url,
    title: '',
    metaDescription: 'Professional insulation services in your area. Contact us for a free estimate.',
    metaDescriptionLength: 75,
    isMetaUnique: false,
    h1Count: 1,
    h2Count: 3,
    h3Count: 2,
    totalWordCount: 450,
    uniqueWordCount: 85,
    templateRatio: 0.81,
    hasFAQ: false,
    questionsAnswered: 0,
    hasSchema: false,
    schemaTypes: [],
    images: { total: 2, withAlt: 1, withoutAlt: 1 },
    readabilityScore: 65,
  })),
  missingMetaDescriptions: [],
  duplicateMetaDescriptions: [
    {
      meta: 'Professional spray foam insulation services. Energy efficient solutions for your home or business. Contact us for a free estimate.',
      pages: generateOrphanPages().slice(0, 78).map(p => p.url),
    },
    {
      meta: 'Expert attic insulation services. Reduce energy bills and improve comfort. Free estimates available.',
      pages: generateOrphanPages().slice(78, 156).map(p => p.url),
    },
  ],
  missingH1: [],
  multipleH1: [],
  pagesWithoutFAQ: [
    '/home-insulation/',
    '/commercial-insulation/',
    '/insulation-removal/',
    '/insulation-company/',
    '/metal-building-insulation/',
    '/pole-barn-insulation/',
    '/warehouse-insulation/',
    '/new-construction-insulation/',
  ],
  pagesWithoutSchema: [
    '/services/',
    '/about-us/',
    ...generateOrphanPages().slice(0, 50).map(p => p.url),
  ],
  imagesWithoutAlt: generateOrphanPages().slice(0, 30).map(p => ({ page: p.url, images: [] })),
  averageWordCount: 420,
  averageUniqueContentRatio: 0.19,
  contentQualityDistribution: {
    poor: 450,
    thin: 170,
    adequate: 80,
    good: 20,
    comprehensive: 6,
  },
};

// Full Report
export const mockReport: SEOReport = {
  generatedAt: new Date().toISOString(),
  siteUrl: 'https://desertsprayfoaming.com',
  summary: {
    criticalIssues: mockIssues.filter(i => i.severity === 'critical').length,
    warnings: mockIssues.filter(i => i.severity === 'warning').length,
    opportunities: mockIssues.filter(i => i.severity === 'opportunity').length,
    overallHealthScore: 28, // Deliberately harsh
  },
  issues: mockIssues,
  linkAnalysis: mockLinkAnalysis,
  blogAnalysis: mockBlogAnalysis,
  contentAnalysis: mockContentAnalysis,
  actionItems: {
    immediate: [
      '[Internal Linking] Add "Nearby Areas" section to all location pages linking to 3-5 adjacent cities',
      '[Content Gaps] Create blog posts for services with zero coverage: home-insulation, insulation-removal, metal-building-insulation',
      '[Internal Linking] Update all blog posts to include 2-3 contextual links to relevant service pages',
      '[Content Quality] Add 200+ words of unique, location-specific content to each location page',
    ],
    shortTerm: [
      '[Technical SEO] Write unique meta descriptions for all location pages',
      '[Content Strategy] Create content calendar for 2-4 blog posts per month',
      '[Internal Linking] Have blog posts link to specific location pages when mentioning areas',
      '[Content Enhancement] Add FAQ sections with schema to all service pages',
    ],
    longTerm: [
      '[Content Strategy] Create detailed case studies for completed projects with before/after photos',
      '[Internal Linking] Implement topic clusters linking blog posts to pillar service pages',
      '[Content Enhancement] Add customer testimonials and reviews to location pages',
    ],
  },
  pageDetails: new Map(),
};
